-- ── Matt prompts — Days 1–30 — universal (pathway null) ──────────────────────
-- Six prompts per day: one thought for the day + five mood responses.
-- Mood values: anxious | triggered | flat | hopeful | struggling
-- Run AFTER migration 006 and seed 006 (which adds the unique constraint).

insert into prompts (role, trigger_type, day_number, moment, mood, pathway, title, brief, sequence) values

-- ── Day 1 ─────────────────────────────────────────────────────────────────────
('matt','day',  1,'morning',null,      null,'Day One',
 'Tell them today is the hardest day, and they only have to get through today — not this week, not forever. Help them understand that what they''re feeling physically right now is the body starting to repair itself, not breaking down. Give them one anchor to hold onto — a glass of water, a person they can call, one small concrete thing. Keep it close and real.',
 1),
('matt','mood', 1,null,'anxious',      null,'Anxious — Day One',
 'Tell them anxiety on Day One is almost universal — it''s neurological, the nervous system recalibrating, not a sign that something is wrong with them. Give them one grounding step to do right now: slow the breathing, feel both feet on the floor, name five things in the room. One thing, not a plan.',
 1),
('matt','mood', 1,null,'triggered',    null,'Triggered — Day One',
 'Name the craving for what it is — the addiction''s strongest move, timed for the hardest moment. Tell them a craving is not a command. Walk them through it: the feeling rises, peaks, and fades whether they act on it or not. Ask them to get through the next 20 minutes. Change location if they can.',
 2),
('matt','mood', 1,null,'flat',         null,'Flat — Day One',
 'Acknowledge the numbness or flatness — tell them the emotional system is adjusting alongside the physical one, and that not feeling anything isn''t the same as things not working. Give them permission to do the minimum today. They don''t need to feel motivated. They just need to not use. That''s the whole job right now.',
 3),
('matt','mood', 1,null,'hopeful',      null,'Hopeful — Day One',
 'Acknowledge the hope without qualifying it — let it be real. Ask them to bank it: write something down, tell someone, notice what''s driving it. Be honest with them too: harder days are coming, and this feeling is something they can come back to when they do.',
 4),
('matt','mood', 1,null,'struggling',   null,'Really struggling — Day One',
 'Speak directly to someone who might be at a breaking point. Don''t try to hold this moment alone — tell them clearly to reach out right now: to a person in their life, to Samaritans on 116 123, or to a doctor if they''re in physical danger. Acknowledge how hard this is without minimising it. Tell them that struggling this much on Day One is common, and that the people who get through it are the ones who ask for help. Keep it short, warm, and point them outward.',
 5),

-- ── Day 2 ─────────────────────────────────────────────────────────────────────
('matt','day',  2,'morning',null,      null,'Day Two — you made it through the night',
 'Tell them that Day Two is often harder than Day One because the adrenaline of starting is gone. The quiet is the challenge now. Acknowledge that and help them find the quiet determination underneath it — they got through yesterday and they can get through today.',
 1),
('matt','mood', 2,null,'anxious',      null,'Anxious — Day Two',
 'The second night is often when anxiety peaks — the body is working hard and the mind catches up. Offer a breathing technique: four counts in, hold for four, four counts out. That''s the whole intervention right now.',
 1),
('matt','mood', 2,null,'triggered',    null,'Triggered — Day Two',
 'Tell them cravings on Day Two can feel stronger than Day One because the novelty is gone and the substance is still talking. Remind them: the craving is memory, not need. It''s the brain running its old circuit. Name what they can do in the next five minutes to interrupt it.',
 2),
('matt','mood', 2,null,'flat',         null,'Flat — Day Two',
 'A second-day crash is real and common. The body is exhausted and the emotions haven''t caught up yet. Tell them flat on Day Two doesn''t mean this isn''t working — it means the work is happening. The minimum is enough today.',
 3),
('matt','mood', 2,null,'hopeful',      null,'Hopeful — Day Two',
 'They made it through the first night. Help them notice one small thing that''s different — even slightly — from how they felt on Day One. Small evidence compounds.',
 4),
('matt','mood', 2,null,'struggling',   null,'Really struggling — Day Two',
 'Two days in and still this hard — that''s not a failure, that''s withdrawal. Tell them their body is doing something enormous right now. And tell them clearly: they don''t have to do this without help. Samaritans are available on 116 123, any time. If they''re in physical danger, they should call a doctor or 999.',
 5),

-- ── Day 3 ─────────────────────────────────────────────────────────────────────
('matt','day',  3,'morning',null,      null,'Day Three — almost through the worst of it',
 'Tell them Day Three is often the hardest physical day — the body working its hardest to rebalance. But it''s also often the turning point. Name what might be happening physically and help them see they''re nearly through the acute phase. Today matters more than they know.',
 1),
('matt','mood', 3,null,'anxious',      null,'Anxious — Day Three',
 'Physical anxiety tends to peak around Day Three. Tell them that directly — this is the height of it, and it will start to ease from here. Give them one physical thing to do: get outside for five minutes, cold water on the face, move the body. Break the loop with the body, not the mind.',
 1),
('matt','mood', 3,null,'triggered',    null,'Triggered — Day Three',
 'Tell them cravings on Day Three are intense but this is the peak — the frequency and strength will reduce from here. The urge is loudest right before it starts to quiet.',
 2),
('matt','mood', 3,null,'flat',         null,'Flat — Day Three',
 'Exhaustion on Day Three is almost universal. The body has been doing heavy work for 72 hours. Tell them flat is the right response to that. Rest is not giving up — rest is the work.',
 3),
('matt','mood', 3,null,'hopeful',      null,'Hopeful — Day Three',
 'They''re nearly through the hardest physical stretch. Ask them to identify one specific thing that feels slightly better than it did 48 hours ago — sleep, appetite, clarity, anything. That''s evidence.',
 4),
('matt','mood', 3,null,'struggling',   null,'Really struggling — Day Three',
 'Day Three is one of the hardest and they should know that''s not them — that''s withdrawal. Tell them this moment is exactly when they need another person, not just this app. Samaritans: 116 123. A GP if they''re in physical distress. Tell them to make one call right now.',
 5),

-- ── Day 4 ─────────────────────────────────────────────────────────────────────
('matt','day',  4,'morning',null,      null,'Day Four — the fog is starting to lift',
 'By Day Four the acute physical withdrawal is usually easing. Name what might be changing — slightly clearer head, a little more energy, maybe a better night''s sleep. Help them see they''re through the worst of it, while being honest that the work isn''t over.',
 1),
('matt','mood', 4,null,'anxious',      null,'Anxious — Day Four',
 'The anxiety is starting to shift from physical to psychological — from the body''s alarm to the mind''s worries. Tell them this is progress, even though it doesn''t feel like it. Ask them what specifically they''re anxious about today. Name it before trying to manage it.',
 1),
('matt','mood', 4,null,'triggered',    null,'Triggered — Day Four',
 'Cravings on Day Four are starting to be more about habit and environment than pure physical need. Help them identify where this one is coming from — time of day, place, emotion. Knowing the pattern is the first step to interrupting it.',
 2),
('matt','mood', 4,null,'flat',         null,'Flat — Day Four',
 'Still flat is fine. Tell them the emotional system takes longer to recover than the physical one. Ask them to do one thing today that has nothing to do with recovery — a walk, some food they like, a conversation with someone. Rest the mental load for an hour.',
 3),
('matt','mood', 4,null,'hopeful',      null,'Hopeful — Day Four',
 'Four days is real progress. Help them notice what''s changed since Day One — even small things: appetite, sleep, thinking. Ask them to hold onto this for the harder days, and tell them those days are survivable because they''ve already survived Day One through Three.',
 4),
('matt','mood', 4,null,'struggling',   null,'Really struggling — Day Four',
 'Hitting a wall on Day Four can feel like the whole thing is falling apart. It isn''t — but it is a sign they need more support than they''re getting. Tell them to contact someone today: a GP, a helpline, a person who knows what''s happening. Carrying this alone on Day Four is too much to ask of themselves.',
 5),

-- ── Day 5 ─────────────────────────────────────────────────────────────────────
('matt','day',  5,'morning',null,      null,'Day Five — the body is through the worst',
 'Tell them the acute physical phase is largely behind them. The challenge is shifting — from survival to sustainability. Help them think about one small thing they can do differently today: drink water, eat something decent, go outside. Start building the basics.',
 1),
('matt','mood', 5,null,'anxious',      null,'Anxious — Day Five',
 'By Day Five, anxiety is often about what comes next — how to stay sober in ordinary life. Help them focus back on just today. They don''t need a plan for the next six months. They need to get through today. Ask them what one thing they''re dreading and help them make it smaller.',
 1),
('matt','mood', 5,null,'triggered',    null,'Triggered — Day Five',
 'Five days in and still getting triggered — that''s normal. Tell them the brain''s reward circuits are still firing the old patterns. What matters is the gap between the urge and acting on it — and that gap is already wider than it was on Day One.',
 2),
('matt','mood', 5,null,'flat',         null,'Flat — Day Five',
 'Low mood is often at its worst in the first two weeks as the brain''s chemistry rebalances. Tell them this specifically — it''s not who they are, it''s the dopamine system recalibrating. One day at a time is not a cliché; it''s literally the only thing that works right now.',
 3),
('matt','mood', 5,null,'hopeful',      null,'Hopeful — Day Five',
 'Five days is a milestone. Help them notice what''s already shifted — physically, mentally, in energy. Ask them to share this with one person — not to perform recovery, but because saying it out loud makes it more real.',
 4),
('matt','mood', 5,null,'struggling',   null,'Really struggling — Day Five',
 'Reaching out when it''s this hard is not weakness — it''s the most effective thing they can do right now. Samaritans: 116 123. Text SHOUT to 85258. A GP. Someone who knows. One call, one message. That''s the whole ask.',
 5),

-- ── Day 6 ─────────────────────────────────────────────────────────────────────
('matt','day',  6,'morning',null,      null,'Day Six — building a new routine',
 'Tell them the first physical crisis is over and the work now is building new habits in the space where the old ones were. Help them think about one habit — small, practical, nothing dramatic — that they can start today. A walk at a certain time. A meal they cook. Something that belongs to recovery, not to using.',
 1),
('matt','mood', 6,null,'anxious',      null,'Anxious — Day Six',
 'By Day Six, anxiety often starts to attach to specific triggers — places, people, times of day associated with using. Help them name one of those triggers and think about what they can do differently when they encounter it. Preparation reduces the power of the trigger.',
 1),
('matt','mood', 6,null,'triggered',    null,'Triggered — Day Six',
 'Tell them to look at when the craving hit. Time of day? After a specific event? A person or place? The brain creates patterns and those patterns are identifiable. Understanding the pattern gives them a moment to choose before the automatic response kicks in.',
 2),
('matt','mood', 6,null,'flat',         null,'Flat — Day Six',
 'Six days in and still flat — tell them this is the reality of early recovery, not a sign that it''s not working. Low mood in the first two weeks is nearly universal. Ask them what the minimum is for today and give them permission to do only that.',
 3),
('matt','mood', 6,null,'hopeful',      null,'Hopeful — Day Six',
 'One more day on top of five. Help them see the compounding effect — each day builds on the last. Ask them what tomorrow looks like and help them find one thing to look forward to, however small.',
 4),
('matt','mood', 6,null,'struggling',   null,'Really struggling — Day Six',
 'Six days in and really struggling is a sign they need more support than they''ve got right now, not a sign that they''re failing. A GP can help with withdrawal support. Samaritans: 116 123. Ask them to make contact today, not tomorrow.',
 5),

-- ── Day 7 ─────────────────────────────────────────────────────────────────────
('matt','day',  7,'morning',null,      null,'One week',
 'Tell them one week is significant — genuinely, not just as a number. The body has done enormous work. Name that clearly. And help them understand that the second week brings different challenges — emotional rather than physical. Different, but survivable.',
 1),
('matt','mood', 7,null,'anxious',      null,'Anxious — One week in',
 'Anxiety at the one-week mark often carries a new edge: the fear of sustaining this. Tell them they don''t need to sustain the whole thing right now — just today, one more time. The only question is today.',
 1),
('matt','mood', 7,null,'triggered',    null,'Triggered — One week in',
 'One week of cravings not acted on is real evidence they can ride them out. Each one resisted changes the brain''s pattern, slowly. The craving is losing ground even when it doesn''t feel like it.',
 2),
('matt','mood', 7,null,'flat',         null,'Flat — One week in',
 'Flat at the one-week mark is so common it has a name — the post-acute crash. Tell them the dopamine system takes weeks to rebalance, not days. They are not stuck. They are healing. Rest and routine are the medicine right now.',
 3),
('matt','mood', 7,null,'hopeful',      null,'Hopeful — One week in',
 'One week is real. Help them feel the weight of it concretely. What has changed? What can they do today that they couldn''t do a week ago? Let the evidence be specific.',
 4),
('matt','mood', 7,null,'struggling',   null,'Really struggling — One week in',
 'Reaching a week and still really struggling tells them they need structured support, not just willpower. A GP, a drug and alcohol service, a recovery group. This isn''t giving in — it''s getting the right level of help. Tell them to make one call today to someone qualified to support them.',
 5),

-- ── Day 8 ─────────────────────────────────────────────────────────────────────
('matt','day',  8,'morning',null,      null,'Second week — a different kind of hard',
 'Tell them the second week is where many people struggle because the physical urgency is gone but the psychological work is just beginning. The motivation from the crisis of Day One has faded. What''s left is quieter and harder to hold onto. Help them find that quiet determination.',
 1),
('matt','mood', 8,null,'anxious',      null,'Anxious — Week two',
 'In the second week, anxiety often shifts to identity: who am I without this? Tell them these are the right questions — they just don''t need answering today. Today is about staying sober. The identity work comes later.',
 1),
('matt','mood', 8,null,'triggered',    null,'Triggered — Week two',
 'Cravings in the second week are increasingly psychological — the brain chasing a feeling rather than the body demanding a substance. Help them notice the emotional state underneath: boredom, loneliness, stress. The craving is a signal, not a command.',
 2),
('matt','mood', 8,null,'flat',         null,'Flat — Week two',
 'Week two is often when anhedonia settles in as the brain''s reward system resets. Tell them this directly: it has a name, it''s expected, it will pass. It is not who they are. The brain is doing chemistry right now, not giving them a verdict on their life.',
 3),
('matt','mood', 8,null,'hopeful',      null,'Hopeful — Week two',
 'Past one week. Help them take stock — not of how far there is to go, but of what''s already real. Sleep, energy, clarity, relationships — something is shifting. Ask them to name it.',
 4),
('matt','mood', 8,null,'struggling',   null,'Really struggling — Week two',
 'Struggling in week two is not a surprise — this is when the pink cloud lifts and the real work starts. And it''s when structured support matters most. GP, drugs and alcohol service, a recovery counsellor. This is the moment for that.',
 5),

-- ── Day 9 ─────────────────────────────────────────────────────────────────────
('matt','day',  9,'morning',null,      null,'Day Nine — sleep is starting to return',
 'Sleep often starts improving around Day Nine. If it hasn''t, that''s also normal — sleep disruption can last weeks. Either way, help them see their body is running a repair process they can support: consistent sleep time, less screen time before bed, a quiet routine.',
 1),
('matt','mood', 9,null,'anxious',      null,'Anxious — Day Nine',
 'Vivid dreams and disrupted sleep are common in the second week and make anxiety worse. Tell them this is temporary. One sleep intervention: same bedtime, no screen for an hour before, write down worries before lying down.',
 1),
('matt','mood', 9,null,'triggered',    null,'Triggered — Day Nine',
 'Evening is often the most vulnerable window — it''s when using used to happen. Help them plan this evening specifically: what will they do from 6pm? Having a plan before the craving arrives is completely different to improvising in the moment.',
 2),
('matt','mood', 9,null,'flat',         null,'Flat — Day Nine',
 'Ask them to find one small thing that gives them even a flicker of something good: food, music, a person, movement. Not to chase it, just to notice it. The reward system is rebuilding and even small signals matter.',
 3),
('matt','mood', 9,null,'hopeful',      null,'Hopeful — Day Nine',
 'Help them pause and take stock. Nine days of choices. Ask them to name two or three things that are better than they were on Day One — not perfect, just better. That''s real and it''s theirs.',
 4),
('matt','mood', 9,null,'struggling',   null,'Really struggling — Day Nine',
 'Being this low nine days in is a sign of how hard withdrawal genuinely is — not a sign they''re weak or that this won''t work. They need a real person right now: Samaritans on 116 123, a helpline, a doctor. Reach out before the evening, not after.',
 5),

-- ── Day 10 ────────────────────────────────────────────────────────────────────
('matt','day', 10,'morning',null,      null,'Day Ten — the gap is getting wider',
 'Tell them that ten days in, the gap between the craving and acting on it is getting wider — even if it doesn''t feel that way. The brain is rewiring slowly. Each day of not using is changing the pattern, even invisibly.',
 1),
('matt','mood',10,null,'anxious',      null,'Anxious — Day Ten',
 'At ten days, anxiety often focuses on social situations — going somewhere using was normal, being around people who don''t know what''s happening. Help them prepare specifically for the next social situation they''re worried about. Concrete preparation beats abstract reassurance.',
 1),
('matt','mood',10,null,'triggered',    null,'Triggered — Day Ten',
 'Ten days of resisted cravings. Help them see that''s ten data points proving the craving always passed. The craving lies — it says "this time is different." Their ten days says it isn''t. That''s evidence.',
 2),
('matt','mood',10,null,'flat',         null,'Flat — Day Ten',
 'Low mood in week two is often at its deepest before it starts to ease. That''s not a promise for today, but it''s true — and knowing where they are in the process matters. Ask them to do one physical thing today: a walk, fresh air, water.',
 3),
('matt','mood',10,null,'hopeful',      null,'Hopeful — Day Ten',
 'Double digits. Help them mark that with something concrete — tell someone, write it down, do something that acknowledges the occasion for themselves. Not a celebration that carries risk. Just an acknowledgement.',
 4),
('matt','mood',10,null,'struggling',   null,'Really struggling — Day Ten',
 'Ten days in and still really struggling — this is the time to escalate support, not push through alone. GP appointment, drug and alcohol service, a crisis line. Struggling at Day Ten is information: they need more help than they have. Ask for it.',
 5),

-- ── Day 11 ────────────────────────────────────────────────────────────────────
('matt','day', 11,'morning',null,      null,'Day Eleven — relationships are shifting',
 'Tell them that people around them are starting to notice something is different. Relationships change in recovery. Help them think about who in their life supports this and who doesn''t — not to make decisions today, but to be clear-eyed about their environment.',
 1),
('matt','mood',11,null,'anxious',      null,'Anxious — Day Eleven',
 'Old routines create anxiety in early recovery — places, times, and habits bound up with using. Acknowledging that specific places or times are hard is useful, not weak. They can avoid them or prepare for them. Either is valid.',
 1),
('matt','mood',11,null,'triggered',    null,'Triggered — Day Eleven',
 'Boredom is one of the most underestimated relapse triggers. Help them name it: is this a craving, or is it boredom and restlessness? If it''s boredom, the answer is engagement, not endurance.',
 2),
('matt','mood',11,null,'flat',         null,'Flat — Day Eleven',
 'The middle of the second week is the grey zone — too far from Day One to have that urgency, too far from a month to have real momentum. Tell them this is exactly where not giving up matters most.',
 3),
('matt','mood',11,null,'hopeful',      null,'Hopeful — Day Eleven',
 'Help them trust the process even when they can''t see the outcome. Ask them to notice one relationship or interaction that feels slightly different — more present, more honest, less complicated.',
 4),
('matt','mood',11,null,'struggling',   null,'Really struggling — Day Eleven',
 'Struggling at eleven days doesn''t mean the first eleven days didn''t count — they absolutely did. And it means they need more support right now. Samaritans: 116 123. Text SHOUT to 85258. One call. One message. Make it before the end of today.',
 5),

-- ── Day 12 ────────────────────────────────────────────────────────────────────
('matt','day', 12,'morning',null,      null,'Day Twelve — the body is still doing its work',
 'Even when they feel stuck emotionally, the body is making real changes they can''t always feel yet — sleep, brain chemistry, energy. The repair is happening. Help them think of one thing they can do to support it today: drink water, move a little, eat something real.',
 1),
('matt','mood',12,null,'anxious',      null,'Anxious — Day Twelve',
 '"Who am I without this?" — the substance was part of the identity. Tell them that question is real and important, but they don''t have to answer it in early recovery. Right now they just have to stay sober. Identity comes later.',
 1),
('matt','mood',12,null,'triggered',    null,'Triggered — Day Twelve',
 'Help them separate emotional triggers from situational ones. A situational trigger — a place, a person, a time of day — they can plan for. An emotional trigger — stress, loneliness, shame — is harder. Which is it today? Naming it is the first step.',
 2),
('matt','mood',12,null,'flat',         null,'Flat — Day Twelve',
 'Sleep quality directly affects mood in recovery, and sleep is still disrupted for many at twelve days. Protecting sleep — consistent time, dark room, no screens — is one of the most effective things they can do right now.',
 3),
('matt','mood',12,null,'hopeful',      null,'Hopeful — Day Twelve',
 'Tell them to notice what''s becoming easier — not good yet, but easier. Getting out of bed, having a conversation, getting through an evening. The ceiling is rising slowly. That''s recovery happening.',
 4),
('matt','mood',12,null,'struggling',   null,'Really struggling — Day Twelve',
 'The addiction is loudest when they''re alone. So don''t be alone with it. Samaritans: 116 123, free and 24 hours. A GP if there are physical symptoms. Another person if they have one. One contact, right now.',
 5),

-- ── Day 13 ────────────────────────────────────────────────────────────────────
('matt','day', 13,'morning',null,      null,'Day Thirteen — nearly two weeks',
 'Tell them tomorrow is two weeks and the approach to milestones can be destabilising — the brain sometimes tries to sabotage when something important is close. Help them stay in today. One more day, the same way they''ve done the last twelve.',
 1),
('matt','mood',13,null,'anxious',      null,'Anxious — Day Thirteen',
 'Anxiety the day before a milestone is common and often surprising. The mind can find reasons to worry when things are going well. Tell them that''s the pattern — noise, not information. Tomorrow takes care of itself.',
 1),
('matt','mood',13,null,'triggered',    null,'Triggered — Day Thirteen',
 '"I''ve almost done two weeks, I can have one to celebrate" — tell them that thought by name. It''s not a reward, it''s a trap. The real reward is tomorrow.',
 2),
('matt','mood',13,null,'flat',         null,'Flat — Day Thirteen',
 'Flat before a milestone can feel wrong — shouldn''t they feel something? Tell them no, they don''t have to feel good to be doing well. Two weeks doesn''t depend on the feeling.',
 3),
('matt','mood',13,null,'hopeful',      null,'Hopeful — Day Thirteen',
 'Help them ride this into tomorrow. Ask them to think about tomorrow morning — what they''ll feel when they wake up at two weeks. That''s worth protecting today.',
 4),
('matt','mood',13,null,'struggling',   null,'Really struggling — Day Thirteen',
 'Struggling the day before a milestone — so close and so hard at the same time. Reach out right now, not after. Samaritans: 116 123. Someone who knows what''s happening. Don''t let tonight be the one that undoes thirteen days.',
 5),

-- ── Day 14 ────────────────────────────────────────────────────────────────────
('matt','day', 14,'morning',null,      null,'Two weeks',
 'Tell them two weeks is real and significant. The body has done its hardest work. Help them mark this not just as a number but as evidence — fourteen choices, fourteen mornings, fourteen days of a different path.',
 1),
('matt','mood',14,null,'anxious',      null,'Anxious — Two weeks in',
 'Two-week anxiety often looks like fear of the future — what does the rest of this look like? Tell them that''s the wrong frame. The question isn''t "how long" — it''s "today." They''ve already answered today fourteen times.',
 1),
('matt','mood',14,null,'triggered',    null,'Triggered — Two weeks in',
 'A craving at two weeks can feel defeating — shouldn''t it be easier by now? Tell them it is getting easier, even if individual cravings still feel intense. The frequency is reducing. The duration is shorter. That''s the trend, even when a single craving feels massive.',
 2),
('matt','mood',14,null,'flat',         null,'Flat — Two weeks in',
 'Post-milestone low is real — the focus of reaching two weeks is gone and the grey is still there. The work continues the same way it always has: one day.',
 3),
('matt','mood',14,null,'hopeful',      null,'Hopeful — Two weeks in',
 'Two weeks earned. Help them feel the weight of that — not the distance still to go, but what''s already real. What''s better? What''s possible now that wasn''t two weeks ago? Let the evidence be specific and their own.',
 4),
('matt','mood',14,null,'struggling',   null,'Really struggling — Two weeks in',
 'Struggling at two weeks tells them they need structured support now — professional support: a GP, a drugs and alcohol service, a counsellor. Accessing professional help at this point is what the people who sustain recovery do.',
 5),

-- ── Day 15 ────────────────────────────────────────────────────────────────────
('matt','day', 15,'morning',null,      null,'Day Fifteen — halfway through the first month',
 'Tell them they''re halfway through the first month. The physical recovery is largely done. The emotional and psychological work is now the main event. Structure, support, honesty, and patience — help them think about which of those they most need right now.',
 1),
('matt','mood',15,null,'anxious',      null,'Anxious — Week three',
 'By week three, anxiety is often about sustaining recovery in real life — going back to situations and demands that were always there. The skills they need for that are built, not taught. They''re already building them. Today''s the practice.',
 1),
('matt','mood',15,null,'triggered',    null,'Triggered — Week three',
 'Cravings at week three tend to be triggered by emotional states rather than physical need. Help them identify the emotion first: is this stress, loneliness, frustration, boredom? Address the emotion, and the craving usually reduces.',
 2),
('matt','mood',15,null,'flat',         null,'Flat — Week three',
 'Name anhedonia for them: the temporary inability to feel pleasure, caused by the dopamine system recovering. It''s neurological. It has a timeline. It lifts. They are not stuck — they are in the middle of a recovery process that takes weeks, not days.',
 3),
('matt','mood',15,null,'hopeful',      null,'Hopeful — Week three',
 'Half a month in and feeling hopeful — ask them what they''re building in the space where using used to be. New habits, new routines, new honesty. That space is being filled with something. Help them see what it is.',
 4),
('matt','mood',15,null,'struggling',   null,'Really struggling — Week three',
 'Struggling at week three is a sign they need more scaffolding around their recovery — a support group, a counsellor, a structured programme. Tell them to ask their GP about what''s available. This is a normal step in recovery, not a failure.',
 5),

-- ── Day 16 ────────────────────────────────────────────────────────────────────
('matt','day', 16,'morning',null,      null,'Day Sixteen — thinking more clearly',
 'Tell them cognitive function is improving around this point — concentration, memory, decision-making are returning. Help them notice that. And gently point out that this new clarity might surface things they''ve been avoiding thinking about. They don''t have to deal with everything at once.',
 1),
('matt','mood',16,null,'anxious',      null,'Anxious — Day Sixteen',
 'Clarity in recovery can bring old anxieties to the surface — things they were numbing that are now available to feel. Tell them this is not a bad sign. They can feel those things without acting on them. Feeling is not the same as being overwhelmed.',
 1),
('matt','mood',16,null,'triggered',    null,'Triggered — Day Sixteen',
 'Help them get better at recognising the emotional state before it becomes a craving. Ask them to look back at the last craving: what was happening ten minutes before it arrived? That''s the real trigger.',
 2),
('matt','mood',16,null,'flat',         null,'Flat — Day Sixteen',
 'Still flat in week three — structure helps: regular food, regular sleep, regular contact with someone who supports their recovery. These aren''t exciting interventions but they''re what moves the dial.',
 3),
('matt','mood',16,null,'hopeful',      null,'Hopeful — Day Sixteen',
 'A good day is a good day to do something that supports the harder ones — write a note to their future self, call someone they''ve been avoiding, take one thing off the list. Use the good days well.',
 4),
('matt','mood',16,null,'struggling',   null,'Really struggling — Day Sixteen',
 'Struggling at sixteen days — that''s a hard day and it needs support. Samaritans: 116 123. Text SHOUT to 85258. One person in their life who knows. Make contact right now, not when it gets worse.',
 5),

-- ── Day 17 ────────────────────────────────────────────────────────────────────
('matt','day', 17,'morning',null,      null,'Day Seventeen — memory and sleep improving',
 'Around this point many people notice sleep improving and memory returning. These are markers of real neurological change. Help them notice that — not just willpower, but the brain and body doing their actual work.',
 1),
('matt','mood',17,null,'anxious',      null,'Anxious — Day Seventeen',
 'Anxiety about the past is common as the mind clears — things hidden by using are now visible. Tell them they don''t have to resolve everything now. The past isn''t going anywhere. Right now the work is staying sober. Everything else has time.',
 1),
('matt','mood',17,null,'triggered',    null,'Triggered — Day Seventeen',
 'Loneliness is one of the most powerful and least-named triggers in recovery. Is this craving about the substance, or about the isolation using used to temporarily relieve? If it''s loneliness, the answer is contact with another person, not willpower.',
 2),
('matt','mood',17,null,'flat',         null,'Flat — Day Seventeen',
 'Keeping going when nothing feels good is the hardest thing recovery asks. And it''s also the thing that builds the most. The days they stay sober without feeling good are the days that compound into real resilience.',
 3),
('matt','mood',17,null,'hopeful',      null,'Hopeful — Day Seventeen',
 'Ask them to look at their sleep, their energy, their appetite. Most people see measurable improvements by this point. Help them name one specific physical change. That change is the body recovering — observable, real, theirs.',
 4),
('matt','mood',17,null,'struggling',   null,'Really struggling — Day Seventeen',
 'Seventeen days and still this hard — that''s information. They need professional support, not just personal resolve. A GP can refer them to drug and alcohol services. A counsellor can help with the psychological weight. Tell them to make that appointment today.',
 5),

-- ── Day 18 ────────────────────────────────────────────────────────────────────
('matt','day', 18,'morning',null,      null,'Day Eighteen — recovery is not linear',
 'Tell them directly: recovery is not a straight line. A hard day at eighteen days doesn''t cancel the seventeen before it. It''s a hard day. They''ve had hard days before and got through them. Help them hold the whole picture, not just today.',
 1),
('matt','mood',18,null,'anxious',      null,'Anxious — Day Eighteen',
 'A difficult day in week three can feel like regression. Tell them it isn''t. Recovery has peaks and troughs — this is a trough, and it''s temporary. Ask them to name what specifically is driving the anxiety today. Often naming it deflates it.',
 1),
('matt','mood',18,null,'triggered',    null,'Triggered — Day Eighteen',
 'When they thought the hard triggers were behind them and one hits — that''s how this works. The brain doesn''t unlearn old patterns in a straight line. A craving at eighteen days isn''t going backwards. They ride it out the same way they always have.',
 2),
('matt','mood',18,null,'flat',         null,'Flat — Day Eighteen',
 'Ask them not to look back or forward right now. Ask them: what''s one thing they can do in the next hour that isn''t about recovery at all? A small pleasure, a distraction, anything that gives the mental weight a rest.',
 3),
('matt','mood',18,null,'hopeful',      null,'Hopeful — Day Eighteen',
 'Help them look back from today: eighteen days ago they were on Day One. Ask them what that person couldn''t imagine that they can do or feel today. That gap is real, earned, and proof of what they''re capable of.',
 4),
('matt','mood',18,null,'struggling',   null,'Really struggling — Day Eighteen',
 'A really hard day at eighteen days is real and painful. And it''s not something they have to manage alone. Samaritans: 116 123. A person who knows. A professional if they have one. Reach out before tonight, not after.',
 5),

-- ── Day 19 ────────────────────────────────────────────────────────────────────
('matt','day', 19,'morning',null,      null,'Day Nineteen — getting more honest with yourself',
 'As the fog clears, self-awareness increases. They''re starting to see their patterns, their triggers, what they need more clearly. That honesty is not comfortable but it''s essential. Help them see it as a tool, not a judgement.',
 1),
('matt','mood',19,null,'anxious',      null,'Anxious — Day Nineteen',
 'Some of the anxiety in week three is the anxiety that was always there underneath — the one the substance was suppressing. Seeing it clearly is the first step to working with it. It''s not new anxiety. It''s old anxiety that''s finally visible.',
 1),
('matt','mood',19,null,'triggered',    null,'Triggered — Day Nineteen',
 'Help them understand what the substance was doing for them emotionally — what it was relieving, suppressing, replacing. Understanding the function it served helps them find different ways to meet that need. That''s not weakness; it''s information.',
 2),
('matt','mood',19,null,'flat',         null,'Flat — Day Nineteen',
 'Flat in week three often means the mind is doing the deeper work. It''s not nothing. Let them rest into it rather than pushing against it. The emotional work of recovery is tiring in a different way from the physical.',
 3),
('matt','mood',19,null,'hopeful',      null,'Hopeful — Day Nineteen',
 'Self-awareness is growing. Ask them what they know about themselves now that they didn''t know three weeks ago. That knowledge is one of the things recovery gives — and it''s theirs to keep.',
 4),
('matt','mood',19,null,'struggling',   null,'Really struggling — Day Nineteen',
 'Struggling at nineteen days is not a verdict on the previous nineteen. It''s a hard moment in a long process. Hard moments need real support. Samaritans: 116 123. FRANK: 0300 123 6600. A GP, a counsellor. Make contact today.',
 5),

-- ── Day 20 ────────────────────────────────────────────────────────────────────
('matt','day', 20,'morning',null,      null,'Day Twenty — three weeks approaching',
 'Tell them three weeks is coming and it''s a genuine milestone. Twenty days is a real foundation — one that most people who start never reach. Help them feel that without making it fragile.',
 1),
('matt','mood',20,null,'anxious',      null,'Anxious — Day Twenty',
 'Social anxiety without the substance is one of the most common things in early recovery — it used to make certain situations manageable. Help them think about one specific situation they''re avoiding and what a small, practical step towards it might look like.',
 1),
('matt','mood',20,null,'triggered',    null,'Triggered — Day Twenty',
 'Social situations and peer pressure are a significant trigger in week three. Help them think about how they want to handle those situations now, not in the moment. A plan made in advance is worth ten times a plan made under pressure.',
 2),
('matt','mood',20,null,'flat',         null,'Flat — Day Twenty',
 'The dopamine system takes 30-90 days to substantially rebalance. They''re not even at a month yet. Flat at twenty days is inside the normal window. It will shift. The timeline is weeks, not days.',
 3),
('matt','mood',20,null,'hopeful',      null,'Hopeful — Day Twenty',
 'Twenty days in. Ask them what they''ve built in the space where using used to be — new habits, new routines, new honesty. That space is being filled with something real. Help them see what it is.',
 4),
('matt','mood',20,null,'struggling',   null,'Really struggling — Day Twenty',
 'Struggling without support is where relapses happen. Samaritans: 116 123. A professional: GP or drugs and alcohol service. Make one call. This is exactly the moment for that.',
 5),

-- ── Day 21 ────────────────────────────────────────────────────────────────────
('matt','day', 21,'morning',null,      null,'Three weeks',
 'Tell them three weeks is real momentum. The physical recovery is largely complete. The emotional and psychological recovery is ongoing — but they have three weeks of evidence that they can do this. Help them feel the weight of that without making it fragile.',
 1),
('matt','mood',21,null,'anxious',      null,'Anxious — Three weeks in',
 'At three weeks, anxiety often turns to the future: what does the next month look like, what about a year? Tell them the future isn''t the question. Today is always the question. They''ve answered it twenty-one times already.',
 1),
('matt','mood',21,null,'triggered',    null,'Triggered — Three weeks in',
 'Celebrations and occasions are a significant trigger — the brain associates them with using. Help them think about how to mark milestones in recovery without triggering the old pattern. What does a real celebration look like for them right now?',
 2),
('matt','mood',21,null,'flat',         null,'Flat — Three weeks in',
 'Three weeks in and not feeling it. Tell them recovery doesn''t arrive on a schedule, and the emotional lift takes longer than the physical one. They''re in the right place. The feelings will catch up.',
 3),
('matt','mood',21,null,'hopeful',      null,'Hopeful — Three weeks in',
 'Three weeks of earned hope. Ask them to name two things: one thing that''s genuinely better, and one thing they''re looking forward to. Not as performance — as a real inventory of what''s real and what''s coming.',
 4),
('matt','mood',21,null,'struggling',   null,'Really struggling — Three weeks in',
 'Three weeks is a real achievement and struggling at three weeks doesn''t erase that. But it does mean they need more support than they currently have. A recovery group, a counsellor, a structured programme. Ask their GP. This is the right moment to ask for the next level.',
 5),

-- ── Day 22 ────────────────────────────────────────────────────────────────────
('matt','day', 22,'morning',null,      null,'Day Twenty-Two — building a new normal',
 'They''re in the part of recovery where it stops being about surviving and starts being about building. New routines, new responses to stress, new ways of spending evenings and weekends. Help them identify one thing they''re actively building rather than just enduring.',
 1),
('matt','mood',22,null,'anxious',      null,'Anxious — Day Twenty-Two',
 'Identity anxiety surfaces in week four: who are they without this? What does their social life look like? These questions don''t need answers in early recovery — they need time and sobriety. The answers come gradually, not in a breakthrough.',
 1),
('matt','mood',22,null,'triggered',    null,'Triggered — Day Twenty-Two',
 'Old relationships and environments are significant triggers in week four. Help them assess their environment honestly: who in their life supports their recovery and who makes it harder? Not to cut people off, but to be clear-eyed about who they spend time with right now.',
 2),
('matt','mood',22,null,'flat',         null,'Flat — Day Twenty-Two',
 'The mood will begin to lift soon for most people. Tell them that directly — they''ve done the hardest part. The brain''s reward system is rebuilding and it will come online. What''s coming is not indefinite flatness.',
 3),
('matt','mood',22,null,'hopeful',      null,'Hopeful — Day Twenty-Two',
 'New habits are forming. Ask them to name one. A new morning routine, a different way of handling evenings, a conversation they couldn''t have had three weeks ago. These are the building blocks of sustained recovery.',
 4),
('matt','mood',22,null,'struggling',   null,'Really struggling — Day Twenty-Two',
 'Week four can be a vulnerable time — the initial resolve has faded and the long stretch is visible. That''s when support matters most. Samaritans: 116 123. A person they trust. A professional. Make contact today.',
 5),

-- ── Day 23 ────────────────────────────────────────────────────────────────────
('matt','day', 23,'morning',null,      null,'Day Twenty-Three — the new relationship with time',
 'One of the real changes in recovery is the experience of time — evenings and weekends that used to be structured around using now need filling differently. Help them think about how they''re using that time and what''s working.',
 1),
('matt','mood',23,null,'anxious',      null,'Anxious — Day Twenty-Three',
 'Unstructured time is one of the biggest anxiety triggers in recovery. Help them plan specifically for their next unstructured window: what will they do, and who will they contact if they need support? Planning in advance changes everything.',
 1),
('matt','mood',23,null,'triggered',    null,'Triggered — Day Twenty-Three',
 'Help them think about what using used to give them in terms of time and structure — an activity, a ritual, a social context. What''s replacing those things? The craving is often for the ritual as much as the substance itself.',
 2),
('matt','mood',23,null,'flat',         null,'Flat — Day Twenty-Three',
 'Help them distinguish between flat and bored. Flat is a mood state — passive and heavy. Bored is restlessness — active and looking for something. If it''s boredom, engagement is the answer. If it''s flat, rest and routine.',
 3),
('matt','mood',23,null,'hopeful',      null,'Hopeful — Day Twenty-Three',
 'Ask them what they''re creating in the space that recovery has opened up. New structure, new habits, new relationships with old ones. That creative work — building a life that works without using — is what sustains long-term recovery.',
 4),
('matt','mood',23,null,'struggling',   null,'Really struggling — Day Twenty-Three',
 'Samaritans: 116 123 right now. FRANK: 0300 123 6600 for specific advice. A GP if they haven''t already spoken to one. Make one call before the evening. Don''t sit with this alone.',
 5),

-- ── Day 24 ────────────────────────────────────────────────────────────────────
('matt','day', 24,'morning',null,      null,'Day Twenty-Four — reward the body',
 'At nearly four weeks, the body has done an enormous amount of healing. Encourage them to do something today that acknowledges that — not as a reward that carries risk, but as genuine care: good food, movement, sleep, something they enjoy. Recovery isn''t only about stopping.',
 1),
('matt','mood',24,null,'anxious',      null,'Anxious — Day Twenty-Four',
 'Anxiety in week four is often more diffuse than the crisis anxiety of Day One — about life and the future rather than immediate survival. The tools are the same: breathing, movement, talking. The register is different, the approach isn''t.',
 1),
('matt','mood',24,null,'triggered',    null,'Triggered — Day Twenty-Four',
 'Fatigue is a significant relapse risk that often goes unacknowledged. Tell them directly: if they''re tired, they''re more vulnerable. The craving that hits when they''re exhausted is harder to resist. Rest is a protective factor, not an indulgence.',
 2),
('matt','mood',24,null,'flat',         null,'Flat — Day Twenty-Four',
 'Sleep quality is directly connected to mood and the brain''s recovery. Ask them about their sleep — is it improving? What''s their sleep routine? Sometimes a single change — consistent wake time, less light before bed — makes a real difference to mood.',
 3),
('matt','mood',24,null,'hopeful',      null,'Hopeful — Day Twenty-Four',
 'Nearly a month. Ask them what physical changes they can see or feel — energy, clarity, skin, sleep. Name them. The body is healing visibly and that''s powerful evidence that the work is real.',
 4),
('matt','mood',24,null,'struggling',   null,'Really struggling — Day Twenty-Four',
 'Six days from a month and this hard — escalate support now, not after. GP, drug and alcohol service, counsellor. Or Samaritans on 116 123 right now. Make contact today. The month is still there to be had.',
 5),

-- ── Day 25 ────────────────────────────────────────────────────────────────────
('matt','day', 25,'morning',null,      null,'Day Twenty-Five — nearly a month',
 'The first month is almost theirs. Twenty-five days is a real foundation — one that most people who start never reach. They''re in the minority now, and that''s because of choices they made every single day.',
 1),
('matt','mood',25,null,'anxious',      null,'Anxious — Day Twenty-Five',
 'Anxiety this close to a milestone often feels like superstition — afraid that naming it or almost having it will cause something to go wrong. Tell them that''s a common fear and it''s not a premonition. The month is theirs if they get through today. Just today.',
 1),
('matt','mood',25,null,'triggered',    null,'Triggered — Day Twenty-Five',
 'Cravings in the final stretch of the first month are often the addiction making one more attempt before a milestone. Tell them that. Name the pattern. They''ve resisted twenty-five cravings already — they know how to do this.',
 2),
('matt','mood',25,null,'flat',         null,'Flat — Day Twenty-Five',
 'Flat this close to a month feels wrong, but it''s okay. The milestone doesn''t depend on feeling a certain way. Twenty-five days of not using is twenty-five days, regardless of the mood.',
 3),
('matt','mood',25,null,'hopeful',      null,'Hopeful — Day Twenty-Five',
 'Five days away from a month. Help them think about how to mark it — something real that belongs to them. A plan for Day Thirty that means something.',
 4),
('matt','mood',25,null,'struggling',   null,'Really struggling — Day Twenty-Five',
 'Five days from a month and feeling this low — reach out, not inward. Samaritans: 116 123. A person who knows what''s happening. The month is still possible and still worth having, but they need support to get there.',
 5),

-- ── Day 26 ────────────────────────────────────────────────────────────────────
('matt','day', 26,'morning',null,      null,'Day Twenty-Six — recovery is making space',
 'One of the things recovery gives is space — for things that were crowded out by using. Ask them what they''re noticing has come back: time, attention, a relationship, an interest. That space is one of the real gifts of this.',
 1),
('matt','mood',26,null,'anxious',      null,'Anxious — Day Twenty-Six',
 'Ask them what they''re putting into the space that''s opened up. Sometimes anxiety in late early recovery is the anxiety of an unfamiliar freedom. What''s replacing the structure using provided? That question is worth sitting with.',
 1),
('matt','mood',26,null,'triggered',    null,'Triggered — Day Twenty-Six',
 'Old patterns of thought can be strong triggers even when the environment is different. Help them notice the thought pattern that arrives before the craving. "There''s the thought" is completely different from "there''s the truth." Name it and don''t follow it.',
 2),
('matt','mood',26,null,'flat',         null,'Flat — Day Twenty-Six',
 'Ask them to look for meaning in the work of recovery itself — not happiness yet, but purpose. The reason they started. The people who benefit. The version of themselves they''re building. Meaning carries through flat moods in a way that happiness can''t.',
 3),
('matt','mood',26,null,'hopeful',      null,'Hopeful — Day Twenty-Six',
 'Help them look forward to what''s becoming possible. Not abstractly — specifically. What will they do, see, or be in a month, in three months? Let the hope be concrete.',
 4),
('matt','mood',26,null,'struggling',   null,'Really struggling — Day Twenty-Six',
 'Struggling at twenty-six days is real and they should take it seriously. Reach out — not push through. Samaritans: 116 123. A GP. Someone who knows. The month is four days away and they deserve support to get there.',
 5),

-- ── Day 27 ────────────────────────────────────────────────────────────────────
('matt','day', 27,'morning',null,      null,'Day Twenty-Seven — the first month is nearly theirs',
 'Three days. Help them hold today well — not racing to the finish, not looking over their shoulder. The same way they''ve done every other day. One day at a time is how they got here and it''s how they get to Day Thirty.',
 1),
('matt','mood',27,null,'anxious',      null,'Anxious — Day Twenty-Seven',
 'Fear of failure when something real is this close. Tell them that''s a very human response and it doesn''t mean anything bad is coming. The anxiety is about how much this matters. Let it matter. And get through today.',
 1),
('matt','mood',27,null,'triggered',    null,'Triggered — Day Twenty-Seven',
 'Three days from a month and a craving hits. Tell them this is the pattern — the hardest moments come at the highest stakes. They''ve been here before. They know it passes. The craving is losing this one, same as it has twenty-six times before.',
 2),
('matt','mood',27,null,'flat',         null,'Flat — Day Twenty-Seven',
 'Nearly there and not feeling it. Three days is not the time to reassess everything — it''s the time to do what they''ve been doing and let Day Thirty arrive. The feeling will catch up with the achievement.',
 3),
('matt','mood',27,null,'hopeful',      null,'Hopeful — Day Twenty-Seven',
 'Three days. Ask them to think about Day Thirty morning — what they''ll feel when they wake up having done a month. Help them hold that image. That''s worth protecting today.',
 4),
('matt','mood',27,null,'struggling',   null,'Really struggling — Day Twenty-Seven',
 'Three days from a month and really struggling — don''t wait it out alone. Samaritans: 116 123. Anyone who knows. A professional. The month is close enough to be worth one more call for help.',
 5),

-- ── Day 28 ────────────────────────────────────────────────────────────────────
('matt','day', 28,'morning',null,      null,'Day Twenty-Eight — two days',
 'Two more days. Not to rush it — just to know it. Help them stay present with today and not let the finish line pull their attention away from the work. They''ve done twenty-eight days the same way: one day at a time.',
 1),
('matt','mood',28,null,'anxious',      null,'Anxious — Day Twenty-Eight',
 'Final stretch anxiety. The closer they are, the higher the stakes feel. Help them come back to today — just this day, the same as always. The anxiety about the outcome is real but it''s not information about what''s going to happen.',
 1),
('matt','mood',28,null,'triggered',    null,'Triggered — Day Twenty-Eight',
 '"I''ve nearly done a month — I''ve earned something." Tell them that thought by name. It''s a very specific kind of craving, dressed up as reward. The real reward is Day Thirty morning. That''s what they''re working towards.',
 2),
('matt','mood',28,null,'flat',         null,'Flat — Day Twenty-Eight',
 'Two days from a month and flat. The emotion doesn''t have to match the achievement. Twenty-eight days of flat is still twenty-eight days. The month is built from choices, not feelings.',
 3),
('matt','mood',28,null,'hopeful',      null,'Hopeful — Day Twenty-Eight',
 'Two days. Help them protect today with intention. Ask them what they''ll do this evening that keeps them close to what''s working.',
 4),
('matt','mood',28,null,'struggling',   null,'Really struggling — Day Twenty-Eight',
 'Two days from a month and really struggling — this is exactly the time to reach out. Not to white-knuckle it. Samaritans: 116 123. Someone who knows. The month is two days away and worth fighting for with real support.',
 5),

-- ── Day 29 ────────────────────────────────────────────────────────────────────
('matt','day', 29,'morning',null,      null,'Day Twenty-Nine — tomorrow',
 'Tomorrow they will have done a month. Help them sit with that for a moment. Not to celebrate yet — just to let it be real. And then help them focus on today, because today is what delivers tomorrow.',
 1),
('matt','mood',29,null,'anxious',      null,'Anxious — Day Twenty-Nine',
 'The last night can carry real anxiety — what happens the day after a month? Tell them Day Thirty-One looks the same as every other day: one more day. The milestone doesn''t change the method. They know how to do this now.',
 1),
('matt','mood',29,null,'triggered',    null,'Triggered — Day Twenty-Nine',
 'One more craving before the month. The craving is the addiction''s last move before a milestone it can''t stop. Twenty-nine nights already resisted. Tonight is tonight. Same as always.',
 2),
('matt','mood',29,null,'flat',         null,'Flat — Day Twenty-Nine',
 'One day away from a month and feeling nothing about it. That''s okay. The month is real whether they feel it or not. Tomorrow morning they will have done it. Tonight is just the last step.',
 3),
('matt','mood',29,null,'hopeful',      null,'Hopeful — Day Twenty-Nine',
 'One day. Help them hold that lightly — not so tightly that tonight feels fragile, but clearly enough to keep it in view. Tomorrow is one day of good choices away.',
 4),
('matt','mood',29,null,'struggling',   null,'Really struggling — Day Twenty-Nine',
 'One day from a month and this hard — please reach out now. Samaritans: 116 123. Someone who knows. Don''t spend tonight alone with this. The month is one night away.',
 5),

-- ── Day 30 ────────────────────────────────────────────────────────────────────
('matt','day', 30,'morning',null,      null,'Thirty days',
 'Tell them thirty days is a real achievement. Not because it''s a number, but because of what it represents: thirty choices, thirty mornings, thirty evenings where they did something different. The body has healed, the brain has changed, and they''ve built something real. Help them feel the weight of that — and then help them understand that this is the foundation, not the finish line.',
 1),
('matt','mood',30,null,'anxious',      null,'Anxious — Thirty days in',
 'Anxiety at a month is often about what comes next. Tell them the method doesn''t change. One day. What they''ve built in thirty days is proof that they can do one day. And that''s all tomorrow will ask of them.',
 1),
('matt','mood',30,null,'triggered',    null,'Triggered — Thirty days in',
 '"I''ve done a month — I can have one." Tell them this thought by name. It''s the most dangerous craving of the first month, because it sounds like a reward. Tell them the truth: one doesn''t work any more. They know that. That''s why they started.',
 2),
('matt','mood',30,null,'flat',         null,'Flat — Thirty days in',
 'Some people don''t feel the emotional lift until six weeks, eight weeks, longer. The dopamine system is on its own schedule. But the month is real, regardless of the mood. They did it.',
 3),
('matt','mood',30,null,'hopeful',      null,'Hopeful — Thirty days in',
 'A month. Help them feel the whole thirty days. Ask them: who were they on Day One and who are they today? That gap is real and they built it. Let them own that completely.',
 4),
('matt','mood',30,null,'struggling',   null,'Really struggling — Thirty days in',
 'Thirty days is a real achievement and struggling on Day Thirty doesn''t take that away. But it does mean they need more support going forward — GP, recovery service, counsellor. Thirty days gives them something to build on. Get the support to keep building.',
 5)

on conflict on constraint prompts_address_unique do nothing;
